services:
  # ================= BACKEND =================
  - type: web
    name: fintrack-backend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # ================= FRONTEND =================
  - type: web
    name: fintrack-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist